### ISSUE TITLE
Failing to create pdf

### ISSUE THREAD

**Issue by limxuan** [aspeddro/pandoc.nvim#1]
`Pandoc output=test.html` works fine but not with pdf whenever i try to export a pdf file it shows this `pandoc: Failed to create something.pdf`

**Comment by aspeddro** [comment]
Closing because it has already been solved through Discord.

> NOTE: to generate a pdf it is necessary to have a pdf-engine installed. More details see https://pandoc.org/MANUAL.html#creating-a-pdf
